/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BeCat {
    'class': string;
  }
  interface BeCatAttributes extends StencilHTMLAttributes {
    'class'?: string;
  }

  interface BeDog {
    'class': string;
  }
  interface BeDogAttributes extends StencilHTMLAttributes {
    'class'?: string;
  }

  interface BeMedia {
    'class': string;
    'src': string;
  }
  interface BeMediaAttributes extends StencilHTMLAttributes {
    'class'?: string;
    'src'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BeCat': Components.BeCat;
    'BeDog': Components.BeDog;
    'BeMedia': Components.BeMedia;
  }

  interface StencilIntrinsicElements {
    'be-cat': Components.BeCatAttributes;
    'be-dog': Components.BeDogAttributes;
    'be-media': Components.BeMediaAttributes;
  }


  interface HTMLBeCatElement extends Components.BeCat, HTMLStencilElement {}
  var HTMLBeCatElement: {
    prototype: HTMLBeCatElement;
    new (): HTMLBeCatElement;
  };

  interface HTMLBeDogElement extends Components.BeDog, HTMLStencilElement {}
  var HTMLBeDogElement: {
    prototype: HTMLBeDogElement;
    new (): HTMLBeDogElement;
  };

  interface HTMLBeMediaElement extends Components.BeMedia, HTMLStencilElement {}
  var HTMLBeMediaElement: {
    prototype: HTMLBeMediaElement;
    new (): HTMLBeMediaElement;
  };

  interface HTMLElementTagNameMap {
    'be-cat': HTMLBeCatElement
    'be-dog': HTMLBeDogElement
    'be-media': HTMLBeMediaElement
  }

  interface ElementTagNameMap {
    'be-cat': HTMLBeCatElement;
    'be-dog': HTMLBeDogElement;
    'be-media': HTMLBeMediaElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
